const blightbaneImagesUrl = 'https://blightbane.io/images'

export const DashImageUrl = `${blightbaneImagesUrl}/icons/cardart_4_53.webp`
export const ArcanistImageUrl = `${blightbaneImagesUrl}/classes/Arcanist_I_M.webp`
export const HunterImageUrl = `${blightbaneImagesUrl}/classes/Hunter_I_F.webp`
export const KnightImageUrl = `${blightbaneImagesUrl}/classes/Knight_I_M.webp`
export const RogueImageUrl = `${blightbaneImagesUrl}/classes/Rogue_I_F.webp`
export const SeekerImageUrl = `${blightbaneImagesUrl}/classes/Seeker_I_M.webp`
export const WarriorImageUrl = `${blightbaneImagesUrl}/classes/Warrior_I_M.webp`
export const SunforgeImageUrl = `${blightbaneImagesUrl}/icons/cardart_5_50.webp`
export const DexImageUrl = `${blightbaneImagesUrl}/dex.webp`
export const StrImageUrl = `${blightbaneImagesUrl}/str.webp`
export const IntImageUrl = `${blightbaneImagesUrl}/int.webp`
export const DexIntImageUrl = `${blightbaneImagesUrl}/dexint.webp`
export const DexStrImageUrl = `${blightbaneImagesUrl}/dexstr.webp`
export const IntStrImageUrl = `${blightbaneImagesUrl}/intstr.webp`
export const HolyImageUrl = `${blightbaneImagesUrl}/holy.webp`
export const NeutralImageUrl = `${blightbaneImagesUrl}/neutral.webp`
export const DanceOfBlightImageUrl = `${blightbaneImagesUrl}/icons/Dance%20of%20Blight_eclypse.webp`
export const AbracadabraImageUrl = `${blightbaneImagesUrl}/icons/cards_metamorphosis_2_48.webp`
export const DantelionImageUrl = `${blightbaneImagesUrl}/monsters/dc_dantelion.webp`
export const RushedForgeryImageUrl = `${blightbaneImagesUrl}/icons/Forgery_eclypse-miniset.webp`
