export const CARD_CATEGORIES: Record<number, string> = {
  [0]: 'Action',
  [1]: 'Item',
  [2]: 'Artifact',
  [3]: 'Conjuration',
  [4]: 'Enchantment',
  [5]: 'Basic Attack',
  [6]: 'Summon',
  [7]: 'Performance',
  [8]: 'Form',
  [9]: 'Hymn',
  [10]: 'Revelation',
  [11]: 'Affix',
  [12]: 'Attunement',
  [13]: 'Equipment',
  [14]: 'Code',
  [15]: 'Ingredient',
  [16]: 'Path',
  [17]: 'Location',
  [18]: 'Offering',
  [19]: 'Mantra',
  [20]: 'Adaptation',
  [21]: 'Edict',
}
